FROM ultralytics/ultralytics:latest

# Install any needed packages specified in requirements.txt
RUN pip install boto3 easyocr
RUN pip uninstall opencv-python opencv-python-headless -y
RUN conda update -n base -c defaults conda -y
RUN conda install -c conda-forge py-opencv openh264 -y
ENV PYTHONUNBUFFERED=TRUE

CMD ["ls"]