jobs:
  CloneRepo:
    resources:
      instance-type: C4
    outputs:
      repo:
        type: volume
    uses: git-checkout@v1
    with:
      url: https://github.com/chymchym1905/auto-time-workflow.git
  
  Infer:
    resources:
      instance-type: C4
    needs: 
      - CloneRepo
    inputs:
      repo: CloneRepo.outputs.repo
    outputs:
      timedData:
        type: dataset
        with: 
          ref: dsty6wlo4e4shys
    uses: script@v1
    with:
      script: |-
        rm -rf /outputs/timedData/*
        cd /inputs/repo
        python downloadvideo.py "https://www.youtube.com/watch?v=Zdk6sVYZABE" "https://www.youtube.com/watch?v=ppSwStqbhV0"
        python infer.py
        python timeruns.py 1 1
        cp -R /inputs/repo/downloads /outputs/timedData
        cp -R /inputs/repo/downloads /outputs/timedData
        cp -R /inputs/repo/downloads /outputs/timedData
      image: chymchym1905/auto-time:v3