jobs:
  CloneRepo:
    resources:
      instance-type: C4
    outputs:
      repo:
        type: volume
    uses: git-checkout@v1
    with:
      url: https://github.com/chymchym1905/auto-time-workflow.git
  
  Infer:
    resources:
      instance-type: C4
    needs: 
      - CloneRepo
    inputs:
      repo: CloneRepo.outputs.repo
    outputs:
      timedData:
        type: dataset
        with: 
          ref: dsty6wlo4e4shys
    uses: script@v1
    with:
      script: |-
        ls
      image: chymchym1905/auto-time:v3