on:
  github:
    branches:
      only: main
jobs:
  CloneRepo:
    outputs:
      repo:
        type: volume
    resources:
      instance-type: C4
    uses: git-checkout@v1
    with:
      url: context.event.github.url
  Infer:
    inputs:
      repo: CloneRepo.outputs.repo
    needs:
    - CloneRepo
    outputs:
      timedData:
        type: dataset
        with:
          ref: dsqxz8zjvp592d5
    resources:
      instance-type: C4
    uses: script@v1
    with:
      image: chymchym1905/auto-time:v3
      script: cd /inputs/repo; python checkgpu.py
